Feature/code 10 login form test custom render
coders-app/coders-app-user-accounts pull request #11
Opened 2023-02-09 19:05 UTC by MMLORENA

Añadido al Login Form que el botón este disabled cuando están los campos de email y password vacíos.
Añadido test con caso de uso del botón disabled y que el campo del input se rellene cuando el usuario teclea.
Añadido a LoginPage el test de que muestre un formulario.

Ahora mismo, la función onSubmit no está testeada porque falta toda la implementación de la petición a la Api. En las próximas features se tendrá que actualizar y testear

2023-02-11 21:16 UTC, mariogl requested changes

2023-02-11 21:16 UTC, mariogl commented on src/components/LoginForm/LoginForm.tsx
> +  const formIsValidate = (): boolean =>
No hace falta que sea una función.

El nombre correcto sería `isFormValid` o `isValid`. Las variables que resuelven a un booleano empiezan por `is` o `has`.

2023-02-11 21:16 UTC, mariogl commented on src/pages/LoginPage/LoginPage.test.tsx
> +      const resultEmailLabel: HTMLLabelElement =
El método `getByLabelText` no es para buscar un label, es para buscar un elemento por su label. No devuelve un label, devuelve en este caso un input. Por tanto no es correcto ni el naming de la variable ni la anotación de tipo.

2023-02-11 21:16 UTC, mariogl commented on src/components/LoginForm/LoginForm.test.tsx
> +    test("Then it should show a text field wit 'Email', 'Password", () => {
with*

2023-02-11 21:16 UTC, mariogl commented on src/components/LoginForm/LoginForm.test.tsx
> +  describe("And the user types 'admin@admin.com' as email and '1234' as passwordin the text fields", () => {
password in*

2023-02-11 21:16 UTC, mariogl commented on src/components/LoginForm/LoginForm.test.tsx
> +      userEvent.type(emailInput, expectedUserEmail);
Lo que teclea el usuario no es lo que se espera, así que las dos variables del Arrange no deberían llamarse _expected..._

2023-02-11 21:16 UTC, mariogl commented on src/components/LoginForm/LoginForm.test.tsx
> +  describe("And the user clicks on the button 'Send' without introduce it's email and password", () => {
En este test no se está haciendo clic.

2023-02-12 13:56 UTC, MMLORENA commented on src/components/LoginForm/LoginForm.tsx
> +  const formIsValidate = (): boolean =>
Toda la razón, no me he dado cuenta del naming y pensaba que debía ser una función para hacer la validación pero ya he visto que es innecesario.

2023-02-12 13:56 UTC, MMLORENA commented on src/pages/LoginPage/LoginPage.test.tsx
> +      const resultEmailLabel: HTMLLabelElement =
Okey, lo había entendido mal.

2023-02-12 13:56 UTC, MMLORENA commented on src/components/LoginForm/LoginForm.test.tsx
> +    test("Then it should show a text field wit 'Email', 'Password", () => {
Cierto 🤣 la h es importante usarla.

2023-02-12 13:56 UTC, MMLORENA commented on src/components/LoginForm/LoginForm.test.tsx
> +  describe("And the user clicks on the button 'Send' without introduce it's email and password", () => {
Cierto, no está bien mentir

2023-02-12 14:22 UTC, mariogl requested changes

2023-02-12 14:22 UTC, mariogl commented on src/components/LoginForm/LoginForm.test.tsx
> +      const emailInput: HTMLInputElement = screen.getByLabelText(emailLabel);
No hace falta la anotación de tipo. No hay ningún sitio donde vayas a usar después alguna propiedad o método que sólo sea de los inputs.

2023-02-13 09:54 UTC, MMLORENA commented on src/components/LoginForm/LoginForm.test.tsx
> +      const emailInput: HTMLInputElement = screen.getByLabelText(emailLabel);
No lo sabía, pero es cierto que no lo usaba para nada porque cuando lo tenía mal tipado no se había roto ni avisado TypeScript.

2023-02-13 18:49 UTC, mariogl approved these changes

2023-02-13 18:53 UTC, merged