Feature/cod 86 send user credentials data
coders-app/coders-app-user-accounts pull request #20
Opened 2023-02-20 20:29 UTC by MMLORENA

Creado carpeta constants con apiPaths & eliminada carpeta store para tener dentro de src una carpeta hooks. 
Eliminado carpeta models y cambiado por un archivo types dentro del hook. 
Añadido invocar a  getLoginCookie  con las credenciales del usuario en Login Form al submitear

2023-02-20 20:33 UTC, mariogl requested changes

2023-02-20 20:33 UTC, mariogl commented on src/components/LoginForm/LoginForm.test.tsx
> +      test("Then it should send user credentials data", async () => {
No estás comprobando que se envían credenciales, estás comprobando que se invoca un método.

2023-02-20 20:36 UTC, MMLORENA commented on src/components/LoginForm/LoginForm.test.tsx
> +      test("Then it should send user credentials data", async () => {
Cambio el test por Then it sould invoke getLoginCookie. ¿Mejor?

2023-02-20 20:37 UTC, mariogl commented on src/components/LoginForm/LoginForm.test.tsx
> +      test("Then it should send user credentials data", async () => {
Sí.

2023-02-20 20:37 UTC, MMLORENA commented on src/components/LoginForm/LoginForm.test.tsx
> +      test("Then it should send user credentials data", async () => {
Ok

2023-02-21 18:29 UTC, mariogl approved these changes

2023-02-21 18:36 UTC, merged