Feature/cod 103 use user error case
coders-app/coders-app-user-accounts pull request #22
Opened 2023-02-21 15:49 UTC by catatarelli

Agregue el try catch en la funcion getLoginCookie de useUser.

Estuve intentando testear el caso de error. Agregue errorHandlers.
Me falta el expect del test ya que no estoy segura si hay que testear que showError se llama con "Wrong credentials" o si el error del context cambio a {message: "Wrong credentials", isError: true}
En cualquiera de los dos casos no estoy segura como mockear o si se podría hacer con un spy.

@coders-app/devs  alguna idea?

2023-02-21 18:26 UTC, MMLORENA requested changes

2023-02-21 18:26 UTC, MMLORENA commented on src/store/hooks/useUser/useUser.ts
> +      showError("Wrong credentials");
Para mi el showError debería ser el mensaje de error que envia la api

2023-02-21 18:26 UTC, MMLORENA commented on src/testUtils/wrappers/WrapperWithProviders.tsx
> +  <UiContextProvider>
En los test vamos a tener que controlar que sea el uiContext de verdad y en otros el uiContext.Provider con un value mockeado

2023-02-21 18:26 UTC, MMLORENA commented on src/store/hooks/useUser/useUser.test.ts
> +
El expect creo que debería ser que se recibe el mensaje de la Api del error. Tendrás que añadirlo en el handler

2023-02-21 18:26 UTC, benjaminrae commented on src/setupTests.ts
>  // expect(element).toHaveTextContent(/react/i)
Podemos quitar estos comentarios?

2023-02-21 18:28 UTC, benjaminrae commented on src/store/hooks/useUser/useUser.test.ts
>    describe("When its method getCookie is invoked with credentials 'amind@admin.com' as email and 'AdminAdmin' as password", () => {
Creo que hay una errata en este describe, deberia ser admin@admin.com

2023-02-21 18:29 UTC, benjaminrae commented on src/store/hooks/useUser/useUser.test.ts
> +  describe("When its method getCookie is invoked and axios rejects", () => {
Podriamos ser mas especifico con el caso de uso? He visto que en los error handlers ponemos que responde con status 404

2023-02-21 18:36 UTC, mariogl commented on src/store/hooks/useUser/useUser.ts
> +      showError("Wrong credentials");
Ben ha propuesto un refactor, que meteremos en sprint 3, para hacer una traducción de errores de API a errores de usuario. Mientras tanto, podemos dejar aquí un mensaje genérico que cubra todos los casos, algo como "Error on login, try again later".

2023-02-21 20:56 UTC, MMLORENA commented on src/store/hooks/useUser/useUser.ts
> +      showError("Wrong credentials");
Perfecto

2023-02-22 12:52 UTC, catatarelli commented
@coders-app/devs 
He hecho un nuevo wrapper para poder pasar una store mockeada y ver si se llama la funcion showError.
No se llama la funcion y no entiendo bien porque.
Esta entrando en el error handler y entra en el catch de la funcion cuando lo tiro el test con debugger, y el coverage tambien muestra que pasa por el catch.

se les ocurre una forma de hacer un spy de la funcion showError real del context, y asi poder usar el wrapper que ya teniamos?

2023-02-22 12:52 UTC, catatarelli commented on src/store/hooks/useUser/useUser.test.ts
>    describe("When its method getCookie is invoked with credentials 'amind@admin.com' as email and 'AdminAdmin' as password", () => {
corregido

2023-02-22 12:52 UTC, catatarelli commented on src/setupTests.ts
>  // expect(element).toHaveTextContent(/react/i)
quitados los comentarios

2023-02-22 20:20 UTC, catatarelli commented
@coders-app/dev gracias a Lore me di cuenta que en useUser estaba usando la funcion showError del useUi y no del context que es lo que quería. 
Ahora si, ya pasa el test del caso de error. 
Esta corregida la errata del test.
Cree el WrapperWithValues, que igual se puede integrar en el WrapperWithProviders que dependiendo si le pasamos un valor opcional de un store renderiza una cosa o la otra.

2023-02-23 10:01 UTC, MMLORENA commented on src/hooks/useUser/useUser.ts
> +      showError("Error on login, try again later");
Esto es un mágic string

2023-02-23 11:29 UTC, merged

2023-02-23 11:33 UTC, catatarelli commented on src/testUtils/wrappers/WrapperWithProviders.tsx
> +  <UiContextProvider>
correcto. Ahora mismo tengo el WrapperWithValues que se puede refactorizar para incluirlo en el WrapperWithProviders y no tener dos

2023-02-23 11:35 UTC, catatarelli commented on src/store/hooks/useUser/useUser.test.ts
> +  describe("When its method getCookie is invoked and axios rejects", () => {
cierto ya lo he especificado ahora

2023-02-23 11:37 UTC, catatarelli commented on src/hooks/useUser/useUser.ts
> +      showError("Error on login, try again later");
lo ves mejor en una variable? lo deje asi ya que este mensaje es solo provisional

2023-02-23 11:37 UTC, catatarelli commented on src/store/hooks/useUser/useUser.test.ts
> +
ahora en el expect veo si showError se ha llamado, aunque cuando agreguemos el reducer habrá que cambiarlo

2023-02-24 08:23 UTC, MMLORENA commented on src/testUtils/wrappers/WrapperWithProviders.tsx
> +  <UiContextProvider>
> @coders-app/dev gracias a Lore me di cuenta que en useUser estaba usando la funcion showError del useUi y no del context que es lo que quería. Ahora si, ya pasa el test del caso de error. Esta corregida la errata del test. Cree el WrapperWithValues, que igual se puede integrar en el WrapperWithProviders que dependiendo si le pasamos un valor opcional de un store renderiza una cosa o la otra.

Yo haría eso, hacer el Wrapper de forma dinámica que en función del test se le pueda pasar una store mockeada o usar el provider de verdad.

2023-02-24 08:24 UTC, MMLORENA commented on src/store/hooks/useUser/useUser.test.ts
> +
Si claro, ahora ya no hace falta en el handler tal y como esta

2023-02-24 08:24 UTC, MMLORENA commented on src/hooks/useUser/useUser.ts
> +      showError("Error on login, try again later");
ok

2023-02-27 17:56 UTC, MMLORENA commented on src/hooks/useUser/useUser.test.tsx
> +const mockNavigate = jest.fn();
Me falta un espacio entre lineas

2023-02-27 17:56 UTC, MMLORENA commented on src/hooks/useUser/useUser.test.tsx
> +      } = renderHook(() => useUser(), { wrapper: WrapperWithProviders });
Añadir enters entre la triple AAA del test