Feature/cod 119 user data in user context
coders-app/coders-app-user-accounts pull request #37
Opened 2023-03-10 16:16 UTC by catatarelli

- Creado el loadUserDataActionCreator y testeado
- Agregado el caso en el userReducer y testeado´
- Agregadas las propiedades name y isAdmin al UserContext
- Implementado el dispatch de loadUserDataAction con la response de verifyUser en el custom hook

2023-03-11 10:34 UTC, mariogl requested changes

2023-03-11 10:34 UTC, mariogl commented on src/store/reducers/userReducer/userReducer.ts
> +        isLogged: true,
Yo quitaría el `isLogged` de este case. Sé que no tiene mucho sentido loadear un usuario si no está logueado, pero por separar cosas creo que el case de login debería loguear y éste sólo debería cargar los datos del usuario.

2023-03-11 10:34 UTC, mariogl commented on src/store/reducers/userReducer/userReducer.test.ts
>      test("Then it should return a new user state with isLogged value true", () => {
En este test decimos que vamos a comprobar que `isLogged` sea true, pero luego estamos comprobando todo el objeto. Creo que para no estar cambiando este test cada vez que cambie la forma de `UserState` (como ha pasado en este commit), sólo deberíamos expectear lo que decimos en la línea 20, es decir, que el nuevo estado tenga una propiedad `isLogged` a true.

2023-03-11 10:34 UTC, mariogl commented on src/store/reducers/userReducer/userReducer.test.ts
> +    test("Then it should return a new user state with name value 'Luis'", () => {
En este test no comprobaría el estado completo y no tendría en cuenta el `isLogged`. Comprobaría que el estado nuevo tiene las propiedades y valores que modifica este caso del reducer.

2023-03-11 16:26 UTC, MMLORENA commented on src/store/reducers/userReducer/userReducer.test.ts
>      test("Then it should return a new user state with isLogged value true", () => {
Me parece bien, cambiado

2023-03-11 16:26 UTC, MMLORENA commented on src/store/reducers/userReducer/userReducer.test.ts
> +    test("Then it should return a new user state with name value 'Luis'", () => {
Okey, hecho en el próximo push

2023-03-11 16:26 UTC, MMLORENA commented on src/store/reducers/userReducer/userReducer.ts
> +        isLogged: true,
Okey, entendido

2023-03-12 10:17 UTC, mariogl approved these changes

2023-03-12 16:03 UTC, MMLORENA commented
@coders-app/devs he añadido los cambios solicitados en la PR y la mergeo para poder continuar con la aplicación ya que necesitamos estos cambios y así no tener tantas ramas abiertas.

2023-03-12 16:03 UTC, merged