Feature/cod 142 continue logged
coders-app/coders-app-user-accounts pull request #43
Opened 2023-03-14 19:00 UTC by MMLORENA

Añadido función hasIsLoggedCookie (acepto sugerencias de naming porque no me convence para nada) para comprobar si existe una cookie con el nombre de la cookie creada en el momento de un login correcto. Es una función que devuelve un boolean para utilizarlo en App para invokar a verifyUser solo cuando haya esa cookie. 

Añadido los test de la función del useCookies y además de App. 

El test del Router lo he tenido que cambiar porque no se ha hecho aún el refactor y como se renderiza App, se ha tenido que añadir el mock

2023-03-15 17:15 UTC, mariogl requested changes

2023-03-15 17:15 UTC, mariogl commented on src/hooks/useCookies/useCookies.ts
> +    if (!cookies.includes(cookieName)) {
Hay que refactorizar esto a un return de una sola línea.

2023-03-15 17:15 UTC, mariogl commented on src/hooks/useCookies/useCookies.ts
Si este custom hook sólo sirve para gestionar una cookie, tenemos que renombrarlo. Ahora parece que tanto el hook como setCookie son cosas genéricas de cookies, pero realmente todo lo que hay aquí está relacionado con la cookie de isLogged.

2023-03-15 17:17 UTC, mariogl requested changes

2023-03-15 17:17 UTC, mariogl commented on src/hooks/useCookies/useCookies.test.ts
> +    test("Then it should be set a cookie with name 'coders_user_accounts_is_logged'", () => {
Typo: "it should set"

2023-03-15 17:17 UTC, mariogl commented on src/hooks/useCookies/useCookies.test.ts
> +    test("Then hasIsLoggedCookie should return true", () => {
"Then **it** should return..."

2023-03-15 17:38 UTC, MMLORENA commented on src/hooks/useCookies/useCookies.ts
> +    if (!cookies.includes(cookieName)) {
cierto!

2023-03-15 17:42 UTC, MMLORENA commented on src/hooks/useCookies/useCookies.test.ts
> +    test("Then it should be set a cookie with name 'coders_user_accounts_is_logged'", () => {
Perfe

2023-03-15 17:42 UTC, MMLORENA commented on src/hooks/useCookies/useCookies.test.ts
> +    test("Then hasIsLoggedCookie should return true", () => {
Ok

2023-03-15 17:53 UTC, MMLORENA commented on src/hooks/useCookies/useCookies.ts
Perfecto, lo renombro el hook a `useIsLoggedCookie` si os parece bien y la función de setCookie a `setIsLoggedCookie`

2023-03-15 18:25 UTC, mariogl requested changes

2023-03-15 18:25 UTC, mariogl commented on src/hooks/useIsLoggedCookie/useIsLoggedCookie.ts
> +    return cookies.includes(cookieName) ? true : false;
Aquí sobra el ternario, la expresión que sigue a `return` ya resuelve a true o a false.

2023-03-16 11:10 UTC, MMLORENA commented on src/hooks/useIsLoggedCookie/useIsLoggedCookie.ts
> +    return cookies.includes(cookieName) ? true : false;
true... ahora que lo dices

2023-03-16 14:35 UTC, mariogl approved these changes
El mensaje del commit ha quedado desactualizado.

2023-03-16 14:51 UTC, mariogl approved these changes

2023-03-16 14:51 UTC, MMLORENA commented
> El mensaje del commit ha quedado desactualizado.

actualizado

2023-03-16 14:54 UTC, merged