Create ProtectedRoute component and tests
coders-app/coders-app-user-accounts pull request #51
Opened 2023-03-29 14:41 UTC by benjaminrae

He creado el componente ProtectedRoute para actuar como guard de las rutas protegidas por login.

He testeado que si el usuario esta logueado se renderiza los children y cuando no esta logueado no se renderiza los children.

Tendremos que testear que se navega a la pagina de login desde app cuando esta implementada con una pagina en el router

2023-03-30 04:37 UTC, isdicoders requested changes

2023-03-30 04:37 UTC, isdicoders commented on src/routers/routes.tsx
> +      { path: routerPaths.apps, element: <ProtectedRoute></ProtectedRoute> },
Las etiquetas de componentes sin contenido deberían ser self-closing.

2023-03-30 07:25 UTC, MMLORENA commented on src/routers/routes.tsx
> +      { path: routerPaths.apps, element: <ProtectedRoute></ProtectedRoute> },
Ya sé que es YAGNI dejarlo, pero no lo quitaría, le pondría un placeholder

2023-03-30 12:13 UTC, Killuina commented on src/components/ProtectedRoute/ProtectedRoute.test.tsx
> +      const renderedChildText = screen.queryByText(childText);
Por saber 🤓, aquí usas queryByText porque estás testeando que no esté?

2023-03-30 12:23 UTC, mariogl commented on src/routers/routes.tsx
> +      { path: routerPaths.apps, element: <ProtectedRoute></ProtectedRoute> },
+1

2023-03-31 10:39 UTC, benjaminrae commented
He añadido un placeholder a la ruta app. Y he actualizado la rama

2023-03-31 11:47 UTC, DI3BOSS commented on src/components/ProtectedRoute/ProtectedRoute.tsx
> +  return isLogged ? <>{children}</> : <Navigate to={routerPaths.login} />;
Me has abierto los ojos. Me estuve peleando con rutas protegidas en el proyecto final y, finalmente, no tuve que dejar como un nice to have. Era mucho limpio de implementar de lo que pensaba.

2023-03-31 15:48 UTC, mariogl commented on src/components/ProtectedRoute/ProtectedRoute.test.tsx
> +      const renderedChildText = screen.queryByText(childText);
@Killuina si ya está aclarado se puede resolver ya la conversación.

2023-03-31 15:49 UTC, mariogl submitted a review, later dismissed

2023-03-31 17:01 UTC, Killuina commented on src/components/ProtectedRoute/ProtectedRoute.test.tsx
> +      const renderedChildText = screen.queryByText(childText);
cierto :)

2023-03-31 18:04 UTC, isdicoders approved these changes

2023-03-31 18:05 UTC, merged