Feature/cod 148 close user menu
coders-app/coders-app-user-accounts pull request #53
Opened 2023-03-31 10:51 UTC by AnnaMaPe

- Implementado cierre del menú de usuario clicando cualquier punto de la página
- Modificado el menu de usuario para mantener la navegación desde este una vez abierto
- Testeado que una vez abierto el menú de usuario se cierra clicando cualquier punto de la página
- Testeado que una vez abierto el menú y clicando el link de navegación, se navega fuera de la LoginPage

@coders-app/devs queda pendiente revisar si testear la navegación fuera de la LoginPage aporta la suficiente confianza al código.

2023-03-31 11:08 UTC, mariogl requested changes

2023-03-31 11:08 UTC, mariogl commented on src/components/Account/Account.test.tsx
> +    test("Then the user menu should close and the log out button should not be shown", () => {
Fíjate que en tu código del test no testeas que el menú se cierra. Tu comprobación es que el botón de logout no se ve.

2023-03-31 11:08 UTC, mariogl commented on src/components/Account/Account.test.tsx
> +      const logOutButton = screen.queryByTestId(logoutButtonText);
Este botón tiene un `testid` sólo para poder encontrarlo cuando no hay usuario logueado y por tanto el botón no tiene texto dentro. Si el usuario es Luis, tenemos que buscar un botón con una L dentro.

2023-03-31 11:08 UTC, mariogl commented on src/components/Account/Account.test.tsx
> +    test("Then it should navigate outside LoginPage", () => {
Esto no es lo que estás comprobando en tu `expect`.

2023-03-31 11:09 UTC, mariogl commented
Hay que testear que al hacer clic en el link de apps, se llama a la función `navigate` del custom hook `useNavigate` pasándole el path "/apps".

2023-03-31 11:10 UTC, mariogl requested changes

2023-03-31 11:10 UTC, mariogl commented on src/components/Account/Account.test.tsx
> +      expect(avatarButton).not.toBeInTheDocument();
Cuando en /apps haya una página, el avatar no va a desaparecer (porque el usuario seguirá logueado), por tanto este test se va a romper.

2023-03-31 11:13 UTC, MMLORENA commented on src/components/Account/Account.test.tsx
> +
¿Deberíamos comprobar en este test que el botón de logout existe y después comprobar que no está después del click en alguna parte del body?

2023-03-31 11:15 UTC, MMLORENA commented on src/components/Account/Account.test.tsx
> +      expect(avatarButton).not.toBeInTheDocument();
Me parece raro si se está queriendo testear lo que describe el test que una navegación de LoginPage la hagamos desde un test unitario de un componente y no desde uno de integración a través de una página de Login

2023-03-31 11:24 UTC, mariogl commented on src/components/Account/Account.test.tsx
> +      const logOutButton = screen.queryByTestId(logoutButtonText);
Rectifico: el testid lo tenía el botón de avatar, el link de logout no tiene ningún testid.

2023-03-31 11:33 UTC, AnnaMaPe commented on src/components/Account/Account.test.tsx
> +    test("Then it should navigate outside LoginPage", () => {
Toda la razón. Error parecido al mencionado en el test del caso de cuando el menú está abierto y se clica cualquier.

2023-03-31 11:37 UTC, AnnaMaPe commented on src/components/Account/Account.test.tsx
> +
¿Te refieres a testear que el logout button se puede clicar cuando el menú está abierto y luego, una vez cerrado, ya no?

2023-03-31 11:41 UTC, AnnaMaPe commented on src/components/Account/Account.test.tsx
> +      const logOutButton = screen.queryByTestId(logoutButtonText);
Entendido. Procedo a modificación.

2023-03-31 11:43 UTC, AnnaMaPe commented on src/components/Account/Account.test.tsx
> +      expect(avatarButton).not.toBeInTheDocument();
Si testamos el useNavigate, ¿entonces sería más correcto hacerlo desde un test unitario?

2023-03-31 11:46 UTC, isdicoders commented on src/components/Account/Account.test.tsx
> +      expect(avatarButton).not.toBeInTheDocument();
No se trata de testear useNavigate, seguimos testeando al componente. Lo que esperamos que haga el componente en este caso de uso es llamar a la función `navigate()` con el string que esperamos.

2023-03-31 11:52 UTC, Killuina commented on src/components/Account/Account.test.tsx
> +      expect(avatarButton).not.toBeInTheDocument();
Cuando el usuario hace click en el componente Link se llama a ```navigate()``` "por detrás", pudiendo testear eso?

2023-03-31 11:55 UTC, AnnaMaPe commented on src/components/Account/Account.test.tsx
> +      expect(avatarButton).not.toBeInTheDocument();
Aquí es donde creo que mes está generando la confusión, al no ver el useNavigate. Reviso a partir de vuestros comentarios.

2023-03-31 12:02 UTC, mariogl commented on src/components/Account/Account.test.tsx
> +      expect(avatarButton).not.toBeInTheDocument();
> Cuando el usuario hace click en el componente Link se llama a `navigate()` "por detrás", pudiendo testear eso?

No, eso ya lo hace la librería y no testeamos la librería. Pero si somos nosotros los que llamamos a navigate, entonces sí lo testeamos.

2023-03-31 12:05 UTC, Killuina commented on src/components/Account/Account.test.tsx
> +      expect(avatarButton).not.toBeInTheDocument();
Vale guay ya decía yo jajaja tiene sentido, confusion is real 😵

2023-03-31 12:06 UTC, AnnaMaPe commented on src/components/Account/Account.test.tsx
> +      expect(avatarButton).not.toBeInTheDocument();
> Tienes razón, me he hecho un lío con el botón de logout. Efectivamente, aquí sólo hay un link, por tanto hay que testear que el usuario cuando hace clic ahí ve el contenido de /apps. Y eso lo testeamos en el test de App.

Llavors, en este caso y se que me repito pero para clarificar, lo que queremos testear es que al clickar el link de Apps, se llama a la función navigate del custom hook useNavigate con el path "/apps".

2023-03-31 12:09 UTC, MMLORENA commented on src/components/Account/Account.test.tsx
> +
No sé si es correcto lo que voy a decir, pero en mi cabeza pondría un expect para comprobar que el menú este abierto y luego en el mismo test otro expect de que logout sea cerrado porque tal y como estoy entendiendo el test, al comprobar que logout no este, podría ser que el test pasará pq nunca se hubiera abierto en un primer momento el menú

2023-03-31 12:10 UTC, mariogl commented on src/components/Account/Account.test.tsx
> +      expect(avatarButton).not.toBeInTheDocument();
Lo que vamos a testear aquí es que existe el link, ya está.

Luego al testear App comprobaremos que al clicar en el link, el usuario ve lo que tiene que ver (la página /apps).

2023-03-31 12:19 UTC, AnnaMaPe commented on src/components/Account/Account.test.tsx
> +
Tienes razón que el test pasa igual si se clica el menú para abrirlo o si no se clica. 
Entonces, no se si estructuralmente será correcto poner los dos expect, pero seria la única manera de comprobar que efectivamente el menú se ha abierto en algún momento.

2023-03-31 12:20 UTC, AnnaMaPe commented on src/components/Account/Account.test.tsx
> +
O sino, añadir el test ("Then") a un mismo bloque donde se testea que el menú se abre? No se si me explico

2023-03-31 12:27 UTC, AnnaMaPe commented on src/components/Account/Account.test.tsx
> +
Procedo a los dos expects, porque la manera que he propuesto anteriormente no seria correcta

2023-03-31 15:45 UTC, mariogl requested changes

2023-03-31 15:45 UTC, mariogl commented on src/components/Account/Account.test.tsx
> +      const logOutButton = screen.queryByText(logoutButtonText);
¿Es necesario volver a buscar el botón?

2023-03-31 15:45 UTC, mariogl commented on src/components/Account/Account.test.tsx
> +const mockedUsedNavigate = jest.fn();
¿Dónde se usa este mock?

2023-04-01 13:25 UTC, MMLORENA commented on src/components/Account/Account.test.tsx
> +      const logOutButton = screen.queryByText(logoutButtonText);
Yo solo he planteado una duda, pero ya me he contestado sola porque el test fallaría si el botón no se pudiera clicar y por tanto ya implicaría que no estaría en la pantalla. Resultado, no, no es necesario volver a buscar el botón.

2023-04-01 13:25 UTC, MMLORENA commented on src/components/Account/Account.test.tsx
> +const mockedUsedNavigate = jest.fn();
No se usa y no es necesario

2023-04-01 14:39 UTC, mariogl commented on src/components/Account/Account.test.tsx
> +      const logOutButton = screen.queryByText(logoutButtonText);
Pero se sigue buscando en la línea 113.

2023-04-01 14:56 UTC, MMLORENA commented on src/components/Account/Account.test.tsx
> +      const logOutButton = screen.queryByText(logoutButtonText);
Creo que no acabo de entender tu pregunta, se busca el avatarButton para poder desplegar el menú y después comprobar que una vez clickado en el document el botón de logout no aparezca. Por eso mi pregunta de buscar primero que esté el logoutButton y después comprobar que tras un click ya no está. Este test me está liando mucho. ¿Puedes explicar mejor qué es necesario testear en este caso de uso?

2023-04-01 15:02 UTC, mariogl commented on src/components/Account/Account.test.tsx
> +      const logOutButton = screen.queryByText(logoutButtonText);
El caso de uso está bien planteado, pero el botón ya se busca en la línea 106, pregunto si hace falta volver a buscarlo en la línea 113 o simplemente expectear que no esté en el documento.

2023-04-01 15:03 UTC, MMLORENA commented on src/components/Account/Account.test.tsx
> +      const logOutButton = screen.queryByText(logoutButtonText);
El la línea 106 se busca el botón del avatar y en la 113 el botón de Logout, son dos botones diferentes

2023-04-01 15:05 UTC, mariogl submitted a review, later dismissed

2023-04-01 15:05 UTC, mariogl commented on src/components/Account/Account.test.tsx
> +      const logOutButton = screen.queryByText(logoutButtonText);
Cierto, pues entonces todo OK.

2023-04-01 15:20 UTC, mariogl approved these changes

2023-04-01 15:20 UTC, merged

2023-04-02 21:15 UTC, AnnaMaPe commented on src/components/Account/Account.test.tsx
> +const mockedUsedNavigate = jest.fn();
Me quedó colgado de antes intentando testear la navigation. Pero efecrtivamete aquí no se usa.