Modify styles in user menu to eliminate movement when opening the menu
coders-app/coders-app-user-accounts pull request #54
Opened 2023-03-31 13:26 UTC by AnnaMaPe

- Modificado estilos en el menú de usuario dando posición fija a la opciones de navegación una vez abierto el menú
- Añadido más margen derecho para dar espacio al texto respetando la alineación con el botón

2023-03-31 15:52 UTC, mariogl requested changes

2023-03-31 15:52 UTC, mariogl commented on src/components/Account/AccountStyled.tsx
> +      position: fixed;
Aquí estamos diciendo que el menú desplegable se posicione según el viewport, pero siempre debería desplegarse del avatar, tienen que ir juntos.

2023-04-01 13:53 UTC, MMLORENA commented
> * Modificado estilos en el menú de usuario dando posición fija a la opciones de navegación una vez abierto el menú
> * Añadido más margen derecho para dar espacio al texto respetando la alineación con el botón

No cumple la convención del naming de rama, debería llamarse bugfix/COD-... se debería haber creado en Jira una tarea si no existe ya

2023-04-01 17:08 UTC, MMLORENA commented on src/components/Account/AccountStyled.tsx
> +      position: fixed;
Ya está cambiado a position absolute y añadido la propiedad `white-space: nowrap` para que el texto no se corte y el width del navigation se ajuste al tamaño del contenedor.

2023-04-01 17:12 UTC, mariogl approved these changes

2023-04-01 18:10 UTC, merged