Bugfix/cod 139 reset form
coders-app/coders-app-user-accounts pull request #68
Opened 2023-04-05 15:11 UTC by AnnaMaPe

- Modificado el reseteo del LoginForm para resetear solo el password cuando el login falle
- Testeado que el reseteo del LoginForm solo reseta el password y no el email

2023-04-06 06:40 UTC, mariogl commented on src/components/LoginForm/LoginForm.test.tsx
> +const userEmail = "admin@admin.com";
@coders-app/devs 
Hay que preparar una subtarea de esta misma tarea para crear un factory de credenciales.

2023-04-06 06:44 UTC, mariogl reviewed
@coders-app/devs 
Veo que el caso de uso en que fallan las credenciales no estaba testeado. Ahora lo ha testeado Anna pero falta comprobar que ante unas credenciales erróneas se muestra el feedback correspondiente al usuario.

2023-04-06 06:44 UTC, mariogl commented on src/components/LoginForm/LoginForm.test.tsx
> +    test("Then the password text field should be reseted to an empty field", async () => {
El test tiene que comprobar un estado, no una acción (a no ser que estemos testeando que se llama a una función). El test tiene que comprobar que el campo está vacío.

2023-04-06 15:26 UTC, AnnaMaPe commented on src/components/LoginForm/LoginForm.test.tsx
> +const userEmail = "admin@admin.com";
Vale, la creo.

2023-04-06 15:33 UTC, AnnaMaPe commented on src/components/LoginForm/LoginForm.test.tsx
> +    test("Then the password text field should be reseted to an empty field", async () => {
Modifico la descripción. 

¿Testeo el caso de las credenciales erróneas y el feedback correspondiente ?

2023-04-06 16:33 UTC, mariogl commented on src/components/LoginForm/LoginForm.test.tsx
> +    test("Then the password text field should be reseted to an empty field", async () => {
Vale

2023-04-07 11:56 UTC, AnnaMaPe commented
- Modificada descripción de los test que comprueba el estado de los campos después de resetar el formulario
- Añadido test para comprobar que sale un mensaje de error cuando el usuario se logea con credenciales incorrectas

2023-04-07 18:39 UTC, mariogl requested changes
¿Seguro que aquí tenemos que mockear el state ya con el mensaje de error? Tenemos que comprobar que el error aparece pero no porque lo ponemos nosotros en el test sino porque las credenciales son erróneas.

2023-04-10 10:30 UTC, AnnaMaPe commented
@mariogl entonces, ¿tendríamos que usar un servidor mockeado para comprobar el error cuando se usan credenciales erroneas?

2023-04-11 18:43 UTC, isdicoders requested changes

2023-04-11 18:43 UTC, isdicoders commented on src/components/LoginForm/LoginForm.test.tsx
>    getLoginCookie: mockLogin,
A este mock le falta el ´jest.requireActual`

2023-04-13 15:16 UTC, AnnaMaPe commented on src/components/LoginForm/LoginForm.test.tsx
>    getLoginCookie: mockLogin,
Cambiado!

2023-04-13 15:42 UTC, AnnaMaPe commented
- Añadido jest.requireActual dentro del módulo mockeado en LoginForm
- Modificar test para comprobar que en la LoginPage se muestra el mensaje de error cuando el usuario introduce credenciales erróneas 
- Eliminar error handler mock innecesario

@mariogl he tenido un poco de lio con el feedback y he visto el mensaje tarde. ¿Muevo este último test a una nueva feature?

2023-04-13 20:08 UTC, mariogl requested changes

2023-04-13 20:08 UTC, mariogl commented on src/pages/LoginPage/LoginPage.test.tsx
> +  describe("When the user types 'admin@admin.com' as email and an incorrect password '1234' and clicks 'send' button", () => {
Un ENTER gigante que haga muchísimo ruido.

2023-04-13 20:08 UTC, mariogl commented on src/pages/LoginPage/LoginPage.test.tsx
> +    test("Then the message 'Error on login, try again later' should be shown", async () => {
Otro ENTER escandalosísimo.

2023-04-13 20:08 UTC, mariogl commented on src/pages/LoginPage/LoginPage.test.tsx
> +      const errorMessageField = await screen.findByText(expectedErrorMessage);
El mensaje de error no se muestra en un `campo`.

2023-04-13 20:09 UTC, mariogl commented
> @mariogl he tenido un poco de lio con el feedback y he visto el mensaje tarde. ¿Muevo este último test a una nueva feature?

Mejor, sí.

2023-04-13 20:44 UTC, AnnaMaPe commented on src/pages/LoginPage/LoginPage.test.tsx
> +  describe("When the user types 'admin@admin.com' as email and an incorrect password '1234' and clicks 'send' button", () => {
Hecho! Se ha oído hasta en Sant Hilari Sacalm

2023-04-13 20:46 UTC, AnnaMaPe commented on src/pages/LoginPage/LoginPage.test.tsx
> +    test("Then the message 'Error on login, try again later' should be shown", async () => {
Hecho! Este se ha oido cerca de Sant Sadurní d'Osormort.

2023-04-13 20:46 UTC, mariogl commented on src/pages/LoginPage/LoginPage.test.tsx
> +    test("Then the message 'Error on login, try again later' should be shown", async () => {
No te inventes nombres.

2023-04-13 20:47 UTC, AnnaMaPe commented on src/pages/LoginPage/LoginPage.test.tsx
> +      const errorMessageField = await screen.findByText(expectedErrorMessage);
Vale, procedo a cambiar el nombre de la variable!

2023-04-14 10:06 UTC, AnnaMaPe commented
- Quitado el test para comprobar que se muestra el mensaje de error cuando el usuario introduce credenciales erróneas de este bugfix

2023-04-14 11:35 UTC, mariogl approved these changes

2023-04-18 03:00 UTC, isdicoders approved these changes

2023-04-18 10:38 UTC, merged