Feature/cod 175 show loading when is loading true
coders-app/coders-app-user-accounts pull request #71
Opened 2023-04-10 14:21 UTC by DI3BOSS

[ ✓ ] Implementado _conditional rendering_ del componente `isLoading` en el `Layout`.
[ ✓ ] Implementado el _dispatching_ de las acciones `showLoading` y `hideLoading` en `useUser`.
[ ✓ ] Testeado, en `useUser.test`, el _dispatching_ de `showLoadingActionCreator` cuando la función  `geLoginCookie` es llamada.
[ ✓ ] Testeado, en `useUser.test`, el _dispatching_ de `hideLoadingActionCreator` cuando la función  ` logoutUser` es llamada.
[ ✓ ] Testeado, en `App` el _conditional rendering_ del componente `isLoading` dentro del `Layout`.

2023-04-10 16:23 UTC, mariogl requested changes

2023-04-10 16:23 UTC, mariogl commented on src/components/Layout/Layout.tsx
> +      {isLoading && <Loading />}
El loading debe ir al final para que esté por encima del resto de elementos.

2023-04-10 16:23 UTC, mariogl commented on src/hooks/useUser/useUser.ts
> +      uiDispatch(hideLoadingActionCreator());
Hay que poner un único `hide`, porque ocurra lo que ocurra, debe ocultarse el loading.

2023-04-10 16:23 UTC, mariogl commented on src/hooks/useUser/useUser.test.tsx
> +      const showLoader = showLoadingActionCreator();
Lo que nos devuelve un action creator es un action, llamémoslo como tal.

2023-04-10 16:23 UTC, mariogl commented on src/hooks/useUser/useUser.test.tsx
> +    test("Then the uiDispatch should be invoked with the showLoadingActionCreator", async () => {
A dispatch no se le invoca con un action creator, sino con una action.

2023-04-10 16:23 UTC, mariogl commented on src/hooks/useUser/useUser.test.tsx
> +    test("Then uiDispatch should be invoked with the hideLoadingActionCreator", async () => {
Igual que en el anterior.

2023-04-11 11:48 UTC, DI3BOSS commented on src/components/Layout/Layout.tsx
> +      {isLoading && <Loading />}
Puesto por debajo

2023-04-11 11:49 UTC, DI3BOSS commented on src/hooks/useUser/useUser.ts
> +      uiDispatch(hideLoadingActionCreator());
[ ✓ ] Arreglado, tanto en `getLoginCookie` como en `logoutUser`.

2023-04-11 11:50 UTC, DI3BOSS commented on src/hooks/useUser/useUser.test.tsx
> +      const showLoader = showLoadingActionCreator();
[ ✓ ]  Cambiado el identificador de la variable que apunta a `showLoadingActionCreator()`

2023-04-11 11:52 UTC, DI3BOSS commented on src/hooks/useUser/useUser.test.tsx
> +    test("Then the uiDispatch should be invoked with the showLoadingActionCreator", async () => {
[ ✓ ]  Corregido el contenido del _Then_ de este caso de test de la suite `useUser.test`.

2023-04-11 15:02 UTC, MMLORENA commented on src/components/App/App.test.tsx
> +      const mockUiDispatch = jest.fn;
¿Para qué usas este mockUiDispatch? Además no es una función, ¿no?

2023-04-11 15:05 UTC, MMLORENA commented on src/components/App/App.test.tsx
> +      const text = screen.getByText(expectedText);
Me despista mucho el naming de la variable con el describe del test.

2023-04-11 20:01 UTC, isdicoders commented on src/hooks/useUser/useUser.ts
> +      uiDispatch(hideLoadingActionCreator());
Ahora hay un `hide` en el `catch` pero ninguno en el `try`. A `hide` se le debe llamar tanto si va bien como si vamal.

2023-04-11 20:05 UTC, isdicoders requested changes

2023-04-11 20:05 UTC, isdicoders commented on src/components/App/App.test.tsx
> +    test("Then Loading component should be rendered", () => {
Nosotros no comprobamos que un componente sea renderizado, el usuario no sabe nada de componentes.

2023-04-11 20:05 UTC, isdicoders commented on src/components/App/App.test.tsx
> +    test("Then Loading component should be rendered", () => {
Además, este caso de uso no está en el When correcto. Cuando se renderiza App no debe verse el loading.

2023-04-12 10:33 UTC, DI3BOSS commented on src/hooks/useUser/useUser.ts
> +      uiDispatch(hideLoadingActionCreator());
vale! ya me parecía raro, ha sido un _misunderstanding_. Lo corrijo, Pero, entonces, ¿a qué te referías con un único `hide`?

2023-04-12 10:55 UTC, DI3BOSS commented on src/components/App/App.test.tsx
> +      const mockUiDispatch = jest.fn;
Para poder usar la `mockUiStore`, que me pide la propiedad `dispatch` y esta, a su vez, necesita un valor de tipo `React.Dispatch<UiAction>`.

Ahora, he tipado mockUiDispatch como `React.Dispatch<UiAction>` y llamado jest.fn().

2023-04-12 11:18 UTC, DI3BOSS commented on src/components/App/App.test.tsx
> +    test("Then Loading component should be rendered", () => {
He añadido un `describe`  distinto a _when it's rendered_  para este caso de uso.

También he corregido, siguiendo la línea de los cambios solicitados por Lorena, que se compruebe no que el componente se renderice, sino que se muestre el texto _loading_ cuando la propiedad `isLoading` de `UiState` está _seteada_ a `true`.

2023-04-12 16:39 UTC, mariogl commented on src/hooks/useUser/useUser.ts
> +      uiDispatch(hideLoadingActionCreator());
Con que no hay que dispatchear la acción de hidear en dos sitios, sólo en uno.

2023-04-12 16:40 UTC, mariogl requested changes

2023-04-12 16:40 UTC, mariogl commented on src/components/App/App.test.tsx
> +      test("Then Loading component should be rendered in Layout with the text 'loading'", () => {
El usuario no sabe lo que es un componente, y "renderizar" un componente no es algo que podamos comprobar. Lo que se comprueba es que el usuario ve lo que tiene que ver.

2023-04-14 11:55 UTC, mariogl commented
Mergeada para poder cerrar para el fin de sprint.

2023-04-14 11:55 UTC, mariogl approved these changes

2023-04-14 11:55 UTC, isdicoders approved these changes

2023-04-14 11:55 UTC, merged