Feature/cod 48 change password feedback
coders-app/coders-app-user-accounts pull request #84
Opened 2023-05-11 12:38 UTC by DI3BOSS

[✓] Creado el esqueleto de `changePassword` en `useUser`, que en un futuro apuntará al `endpoint` para cambios de contraseñas. Para poder generar un `error` que me envíe al `catch`, he usado un `axios.get()`.
[✓] Creado el `handler` para el _testing_. Tanto este como el `axios.get()` se podrán refactorizar con la _url_ al `endpoint` correcto, cuando este se implemente en el _back_.
[✓] Refactorizado `PasswordForm` para enviar el nuevo `password` que el usuario que introduzca a `changePassword` de `useUser`, y enseñar el _feedback_ de error al usuario. 
[✓] Refactorizados los _tests_ de `PasswordForm`.
[✓] Añadidos casos de _feedback_ de error de `changePassword` a la suite de tests de `useUser`.

2023-05-13 12:46 UTC, mariogl requested changes

2023-05-13 12:46 UTC, mariogl commented on src/components/PasswordForm/PasswordForm.tsx
> +        ></input>
En JSX, las etiquetas sin contenido se autocierran en la misma apertura (como estaba antes)

2023-05-13 12:46 UTC, mariogl commented on src/components/PasswordForm/PasswordForm.tsx
> +    onSubmit: async (userNewPassowrd) => {
Esta comunicación con el custom hook la debería hacer la función submitHandler que se recibía por props.

2023-05-13 12:46 UTC, mariogl commented on src/components/PasswordForm/PasswordForm.tsx
> +  onClick?: () => void;
¿Por qué has cambiado la función submitHandler que había antes?

2023-05-13 12:46 UTC, mariogl commented on src/components/PasswordForm/PasswordForm.tsx
> +        onClick={onClick}
En el onClick de un submit no vinculamos nada, tiene que ser en el onSubmit del form.

2023-05-14 14:41 UTC, isdicoders commented
@DI3BOSS pillo esta tarea para cerrarla el finde.

2023-05-14 20:07 UTC, closed without merging